"""Rename user table to users

Revision ID: 3057b9d5a9e3
Revises: 22f759fe7449
Create Date: 2025-08-29 07:31:50.391537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3057b9d5a9e3'
down_revision = '22f759fe7449'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###