"""add_organizations_and_enhanced_auth

Revision ID: 7382c8db9b60
Revises: 06346deaa6ae
Create Date: 2025-08-29 08:30:34.133694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7382c8db9b60'
down_revision = '06346deaa6ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###